apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: hello-world-pipeline
  name: hello-world-pipeline
spec:
  source:
    git:
      ref: master
      uri: https://github.com/arttuladhar/hello-node
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers:
    - github:
        secret: secret
      type: GitHub
    - generic:
        secret: secret
      type: Generic